// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKnwj3Rja9-zWp09NePGG-vK-PH3earM',
    appId: '1:667732346893:web:343ee16def801c89b1ad44',
    messagingSenderId: '667732346893',
    projectId: 'fir-authentication-d8b4d',
    authDomain: 'fir-authentication-d8b4d.firebaseapp.com',
    storageBucket: 'fir-authentication-d8b4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiGUV298MGAcNwFE4BWYAu6Kab5Blg1ek',
    appId: '1:667732346893:android:d4b11d63ac03dc8bb1ad44',
    messagingSenderId: '667732346893',
    projectId: 'fir-authentication-d8b4d',
    storageBucket: 'fir-authentication-d8b4d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpKnwj3Rja9-zWp09NePGG-vK-PH3earM',
    appId: '1:667732346893:web:4b2b4d806fe00098b1ad44',
    messagingSenderId: '667732346893',
    projectId: 'fir-authentication-d8b4d',
    authDomain: 'fir-authentication-d8b4d.firebaseapp.com',
    storageBucket: 'fir-authentication-d8b4d.firebasestorage.app',
  );
}
