name: weather_forcast_app
description: "A simple modular weather forecast UI in Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  weather_icons: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true